#!/usr/bin/env python3
"""
Telegram Bot - Render.com version (uses StringSession for userbot).
Set TELETHON_SESSION env var with the session string generated by generate_session.py
"""

import os
import asyncio
import sqlite3
import logging
from datetime import datetime

from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, ChatMemberUpdated
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    ChatMemberHandler,
    ContextTypes,
    filters,
)
from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.tl.functions.channels import JoinChannelRequest, LeaveChannelRequest
from telethon.errors import (
    UserAlreadyParticipantError,
    ChannelPrivateError,
    InviteHashExpiredError,
    FloodWaitError,
    SessionPasswordNeededError,
)

# ─── Config ───────────────────────────────────────────────────────────────────
BOT_TOKEN       = os.environ["TELEGRAM_BOT_TOKEN"]
API_ID          = int(os.environ["TELEGRAM_API_ID"])
API_HASH        = os.environ["TELEGRAM_API_HASH"]
PHONE           = os.environ.get("TELEGRAM_PHONE", "")
MY_CHANNEL      = os.environ.get("MY_CHANNEL", "@lliili")
TELETHON_SESSION = os.environ.get("TELETHON_SESSION", "")

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

# ─── Database ─────────────────────────────────────────────────────────────────
DB_PATH = os.path.join(os.path.dirname(__file__), "users.db")


def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS users (
            user_id     INTEGER PRIMARY KEY,
            username    TEXT,
            first_name  TEXT,
            channel     TEXT,
            joined_at   TEXT,
            is_active   INTEGER DEFAULT 1
        )
    """)
    conn.commit()
    conn.close()


def save_user(user_id: int, username, first_name, channel: str):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        INSERT INTO users (user_id, username, first_name, channel, joined_at, is_active)
        VALUES (?, ?, ?, ?, ?, 1)
        ON CONFLICT(user_id) DO UPDATE SET
            username   = excluded.username,
            first_name = excluded.first_name,
            channel    = excluded.channel,
            joined_at  = excluded.joined_at,
            is_active  = 1
    """, (user_id, username, first_name, channel, datetime.utcnow().isoformat()))
    conn.commit()
    conn.close()


def get_user_channel(user_id: int):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("SELECT channel FROM users WHERE user_id = ? AND is_active = 1", (user_id,))
    row = c.fetchone()
    conn.close()
    return row[0] if row else None


def deactivate_user(user_id: int):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("SELECT channel FROM users WHERE user_id = ? AND is_active = 1", (user_id,))
    row = c.fetchone()
    if row:
        c.execute("UPDATE users SET is_active = 0 WHERE user_id = ?", (user_id,))
        conn.commit()
    conn.close()
    return row[0] if row else None


def get_all_active_users():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("SELECT user_id, username, first_name, channel, joined_at FROM users WHERE is_active = 1")
    rows = c.fetchall()
    conn.close()
    return rows


# ─── Userbot ──────────────────────────────────────────────────────────────────
userbot: TelegramClient | None = None
pending_auth: dict = {}


async def init_userbot():
    global userbot
    if TELETHON_SESSION:
        try:
            client = TelegramClient(StringSession(TELETHON_SESSION), API_ID, API_HASH)
            await client.connect()
            if await client.is_user_authorized():
                userbot = client
                me = await userbot.get_me()
                logger.info("Userbot started as: %s (@%s)", me.first_name, me.username)
                return
            else:
                await client.disconnect()
                logger.warning("TELETHON_SESSION is set but not authorized.")
        except Exception as e:
            logger.error("Failed to init userbot from session string: %s", e)
    else:
        logger.warning("TELETHON_SESSION not set. Use /auth to authenticate.")


async def userbot_join(channel: str) -> bool:
    if not userbot:
        logger.warning("Userbot unavailable, cannot join %s", channel)
        return False
    try:
        await userbot(JoinChannelRequest(channel))
        logger.info("Userbot joined: %s", channel)
        return True
    except UserAlreadyParticipantError:
        return True
    except FloodWaitError as e:
        logger.warning("FloodWait %ss joining %s", e.seconds, channel)
        return False
    except (ChannelPrivateError, InviteHashExpiredError) as e:
        logger.warning("Cannot join %s: %s", channel, e)
        return False
    except Exception as e:
        logger.error("Error joining %s: %s", channel, e)
        return False


async def userbot_leave(channel: str) -> bool:
    if not userbot:
        return False
    try:
        await userbot(LeaveChannelRequest(channel))
        logger.info("Userbot left: %s", channel)
        return True
    except Exception as e:
        logger.error("Error leaving %s: %s", channel, e)
        return False


# ─── /auth — interactive userbot authentication via chat ──────────────────────
async def cmd_auth(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global userbot
    user = update.effective_user

    if userbot and await userbot.is_user_authorized():
        me = await userbot.get_me()
        await update.message.reply_text(
            f"✅ الحساب متصل بالفعل!\n👤 {me.first_name} (@{me.username})"
        )
        return

    if not PHONE:
        await update.message.reply_text("❌ متغير TELEGRAM_PHONE غير محدد.")
        return

    try:
        client = TelegramClient(StringSession(), API_ID, API_HASH)
        await client.connect()
        result = await client.send_code_request(PHONE)
        pending_auth[user.id] = {
            "client": client,
            "phone_code_hash": result.phone_code_hash,
            "step": "code",
        }
        await update.message.reply_text(
            f"📱 تم إرسال رمز التحقق إلى `{PHONE}`\n\n"
            "أرسل الرمز هنا مباشرةً (مثال: `12345`):",
            parse_mode="Markdown",
        )
    except Exception as e:
        logger.error("Auth start error: %s", e)
        await update.message.reply_text(f"❌ خطأ: {e}")


async def handle_auth_code(update: Update, context: ContextTypes.DEFAULT_TYPE) -> bool:
    global userbot
    user = update.effective_user
    auth = pending_auth.get(user.id)
    if not auth:
        return False

    text = update.message.text.strip()
    client: TelegramClient = auth["client"]

    if auth["step"] == "code":
        try:
            await client.sign_in(PHONE, text, phone_code_hash=auth["phone_code_hash"])
            userbot = client
            me = await userbot.get_me()
            session_str = client.session.save()
            del pending_auth[user.id]
            await update.message.reply_text(
                f"✅ تم تسجيل الدخول بنجاح!\n👤 {me.first_name} (@{me.username})\n\n"
                f"🔑 احفظ هذا السيشن في المتغيرات السرية باسم `TELETHON_SESSION`:\n\n"
                f"`{session_str}`\n\n"
                "البوت الآن جاهز للاشتراك في قنوات الأعضاء تلقائياً 🎉",
                parse_mode="Markdown",
            )
            logger.info("Userbot authenticated as %s", me.first_name)
        except SessionPasswordNeededError:
            auth["step"] = "2fa"
            await update.message.reply_text(
                "🔐 الحساب محمي بكلمة مرور إضافية (2FA).\nأرسل كلمة المرور:"
            )
        except Exception as e:
            logger.error("Sign-in error: %s", e)
            await update.message.reply_text(f"❌ رمز خاطئ أو منتهي. حاول /auth مجدداً.\nالخطأ: {e}")
            del pending_auth[user.id]
            await client.disconnect()
        return True

    if auth["step"] == "2fa":
        try:
            await client.sign_in(password=text)
            userbot = client
            me = await userbot.get_me()
            session_str = client.session.save()
            del pending_auth[user.id]
            await update.message.reply_text(
                f"✅ تم تسجيل الدخول بنجاح!\n👤 {me.first_name} (@{me.username})\n\n"
                f"🔑 احفظ هذا السيشن في المتغيرات السرية باسم `TELETHON_SESSION`:\n\n"
                f"`{session_str}`\n\n"
                "البوت الآن جاهز للاشتراك في قنوات الأعضاء تلقائياً 🎉",
                parse_mode="Markdown",
            )
            logger.info("Userbot authenticated (2FA) as %s", me.first_name)
        except Exception as e:
            logger.error("2FA error: %s", e)
            await update.message.reply_text(f"❌ كلمة مرور خاطئة. حاول /auth مجدداً.\nالخطأ: {e}")
            del pending_auth[user.id]
            await client.disconnect()
        return True

    return False


# ─── Bot Handlers ─────────────────────────────────────────────────────────────
async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    channel_link = f"https://t.me/{MY_CHANNEL.lstrip('@')}"
    keyboard = [[InlineKeyboardButton("✅ تحقق من الاشتراك", callback_data="check_sub")]]
    text = (
        f"أهلاً {user.first_name}! 👋\n\n"
        f"للاستفادة من هذا البوت يرجى الاشتراك في قناتنا أولاً:\n"
        f"📢 {channel_link}\n\n"
        "بعد الاشتراك اضغط على الزر أدناه للتحقق ✅"
    )
    await update.message.reply_text(text, reply_markup=InlineKeyboardMarkup(keyboard))


async def cb_check_sub(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    user = query.from_user

    try:
        member = await context.bot.get_chat_member(MY_CHANNEL, user.id)
        subscribed = member.status in ("member", "administrator", "creator")
    except Exception as e:
        logger.warning("Membership check error for %s: %s", user.id, e)
        await query.edit_message_text(
            "⚠️ حدث خطأ في التحقق. تأكد من أن البوت مشرف في القناة وحاول مجدداً."
        )
        return

    if subscribed:
        existing_channel = get_user_channel(user.id)
        if existing_channel:
            await query.edit_message_text(
                f"✅ أنت مشترك بالفعل!\n\n"
                f"📢 قناتك المسجّلة: {existing_channel}\n\n"
                "لا يمكن تسجيل أكثر من قناة واحدة. "
                "إذا غادرت قناتنا سنغادر قناتك تلقائياً."
            )
            return
        context.user_data["awaiting_channel"] = True
        await query.edit_message_text(
            "✅ تم التحقق من اشتراكك!\n\n"
            "الآن أرسل يوزرنيم قناتك أو رابطها لأشترك بها:\n"
            "مثال: @mychannel أو https://t.me/mychannel"
        )
    else:
        channel_link = f"https://t.me/{MY_CHANNEL.lstrip('@')}"
        keyboard = [[InlineKeyboardButton("✅ تحقق مجدداً", callback_data="check_sub")]]
        await query.edit_message_text(
            f"❌ أنت لم تشترك في القناة بعد!\n\n"
            f"اشترك أولاً ثم اضغط تحقق:\n📢 {channel_link}",
            reply_markup=InlineKeyboardMarkup(keyboard),
        )


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if await handle_auth_code(update, context):
        return

    user = update.effective_user

    existing_channel = get_user_channel(user.id)
    if existing_channel:
        await update.message.reply_text(
            f"⚠️ لديك قناة مسجّلة بالفعل: {existing_channel}\n\n"
            "لا يمكن تسجيل أكثر من قناة واحدة."
        )
        return

    if not context.user_data.get("awaiting_channel"):
        keyboard = [[InlineKeyboardButton("✅ تحقق من الاشتراك", callback_data="check_sub")]]
        await update.message.reply_text(
            "يرجى الاشتراك في قناتنا والتحقق أولاً.\nاضغط /start للبدء.",
            reply_markup=InlineKeyboardMarkup(keyboard),
        )
        return

    text = update.message.text.strip()

    if "t.me/" in text:
        channel = "@" + text.split("t.me/")[-1].strip("/").split("?")[0]
    elif text.startswith("@"):
        channel = text
    else:
        channel = "@" + text

    if channel.lower() == MY_CHANNEL.lower():
        await update.message.reply_text("⚠️ لا يمكنك إرسال قناتنا الخاصة.")
        return

    msg = await update.message.reply_text("⏳ جاري الاشتراك في قناتك…")
    success = await userbot_join(channel)

    if success:
        save_user(user.id, user.username, user.first_name, channel)
        context.user_data["awaiting_channel"] = False
        await msg.edit_text(
            f"🎉 تم الاشتراك في قناتك {channel} بنجاح!\n\n"
            "تم حفظ معلوماتك. إذا غادرت قناتنا سنغادر قناتك تلقائياً 👋"
        )
    else:
        await msg.edit_text(
            "❌ فشل الاشتراك في قناتك. يرجى التأكد من:\n"
            "• صحة اليوزرنيم / الرابط\n"
            "• أن القناة عامة (Public)\n\n"
            "أرسل اليوزرنيم مجدداً."
        )


async def handle_chat_member(update: Update, context: ContextTypes.DEFAULT_TYPE):
    result: ChatMemberUpdated = update.chat_member
    chat_username = result.chat.username or ""
    if f"@{chat_username}".lower() != MY_CHANNEL.lower():
        return

    old_status = result.old_chat_member.status
    new_status = result.new_chat_member.status
    user_id    = result.new_chat_member.user.id

    was_member = old_status in ("member", "administrator", "creator", "restricted")
    now_left   = new_status in ("left", "kicked", "banned")

    if was_member and now_left:
        logger.info("User %s left %s — leaving their channel", user_id, MY_CHANNEL)
        user_channel = deactivate_user(user_id)
        if user_channel:
            await userbot_leave(user_channel)


async def cmd_users(update: Update, context: ContextTypes.DEFAULT_TYPE):
    users = get_all_active_users()
    if not users:
        await update.message.reply_text("لا يوجد أعضاء مسجلون حتى الآن.")
        return
    lines = [f"👥 الأعضاء المسجلون ({len(users)}):\n"]
    for uid, uname, fname, channel, joined in users:
        uname_str = f"@{uname}" if uname else str(uid)
        lines.append(f"• {fname or uname_str} ({uname_str}) → {channel}\n  انضم: {joined[:10]}")
    await update.message.reply_text("\n".join(lines))


# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    init_db()
    logger.info("Database initialised at %s", DB_PATH)

    app = Application.builder().token(BOT_TOKEN).build()

    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(CommandHandler("auth",  cmd_auth))
    app.add_handler(CommandHandler("users", cmd_users))
    app.add_handler(CallbackQueryHandler(cb_check_sub, pattern="^check_sub$"))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    app.add_handler(ChatMemberHandler(handle_chat_member, ChatMemberHandler.CHAT_MEMBER))

    async def post_init(application: Application) -> None:
        await init_userbot()

    app.post_init = post_init

    logger.info("Starting bot… (polling)")
    app.run_polling(
        allowed_updates=["message", "callback_query", "chat_member"],
        drop_pending_updates=True,
    )


if __name__ == "__main__":
    main()
